version: '3.8'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  pojang-back:
    image: bny1324/pojang-be:v1
    ports:
      - 80:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://${DB_HOST}:3306/pojang?characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    depends_on:
      - redis

# scp test
