version: '3.8'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  pojang-back:
    image: pojang-back:v1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://host.docker.internal:3306/pojang
    depends_on:
      - redis
