# depl
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-depl
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
---
# service yml 추가
apiVersion: v1
kind: Service
metadata:
  # ingress와 연결될 서비스 명
  name: redis-service
spec:
  # ClusterIP는 클러스터 내부에서만 접근가능한 Service를 생성
  type: ClusterIP
  ports:
  - name: http
    # pod의 외부포트
    port: 6379
    # 서비스와 연결해줄 pod의 내부 포트
    targetPort: 6379
    # depl의 labels과 맞추기
  selector:
    app: redis
